### ISSUE TITLE
Anyone still using this?

### ISSUE THREAD

**Issue by daveteu** [TBXark/g4vercel#1]
This is one of the few golang routers i see that can be used for vercel platform. Anyone using this to verify it's still working, since the last update was 2 years ago.

The codes all looks alright though.

**Comment by tbxark** [comment]
https://github.com/TBXark/g4vercel/blob/b104f2daa04275ae982d74f6913ad82665dfef53/gee.go#L82-L97

You can use any router library for go and use it by adding an adaper 
```go
func Handle(w http.ResponseWriter, req *http.Request)
```
This library is relatively simple and lightweight, and no bugs have been found so far.

**Comment by daveteu** [comment]
thank u. have u tried gofiber?

**Comment by tbxark** [comment]
`gofiber` is too complicated for vercel
