### ISSUE TITLE
Middleware still calls c.Next despite returning

### ISSUE THREAD

**Issue by daveteu** [TBXark/g4vercel#2]
Since I cannot use the rs/cors package, i decided to write simple cors.

```
server.Use(func(c *Context) {
		origin := c.Req.Header.Get("Origin")

		if !slices.Contains(allowedOrigins, origin) {
			c.JSON(http.StatusBadRequest, H{"ok": false, "message": "cors"})
			return
		} else {
			c.Next()
		}

	})
```

Despite having the middleware, it still calls the next route.

**Comment by tbxark** [comment]
https://github.com/TBXark/g4vercel/blob/b104f2daa04275ae982d74f6913ad82665dfef53/context.go#L46-L50

You must use `c.Fail(http.StatusBadRequest, H{"ok": false, "message": "cors"})` to break this loop
